export const SET_CONFIGURATION = 'CUSTOM_PACKS/SET_CONFIGURATION'
export const SET_AVAILABLE_PRODUCTS = 'CUSTOM_PACKS/SET_AVAILABLE_PRODUCTS'
export const SET_PRECONFIGURED_PRODUCTS = 'CUSTOM_PACKS/SET_PRECONFIGURED_PRODUCTS'
export const SET_CATEGORY_ID = 'CUSTOM_PACKS/SET_CATEGORY_ID'
export const INIT_PACK = 'CUSTOM_PACKS/INIT_PACK'
export const ADD_TO_PACK = 'CUSTOM_PACKS/ADD_TO_PACK'
export const REMOVE_FROM_PACK = 'CUSTOM_PACKS/REMOVE_FROM_PACK'

