export const SET_CONFIGURATION = 'CUSTOM_PACKS/SET_CONFIGURATION'
export const SET_AVAILABLE_PRODUCTS = 'CUSTOM_PACKS/SET_AVAILABLE_PRODUCTS'
export const SET_PRECONFIGURED_PRODUCTS = 'CUSTOM_PACKS/SET_PRECONFIGURED_PRODUCTS'
export const SET_CATEGORY_ID = 'CUSTOM_PACKS/SET_CATEGORY_ID'
